#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'LyRacDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'ReactiveCocoa', '~> 5.0.0'
pod 'SnapKit'
  # Pods for LyRacDemo

  target 'LyRacDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LyRacDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
