source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '9.0'

target 'LyRacDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'ReactiveCocoa'
pod 'SnapKit'
  # Pods for LyRacDemo

  target 'LyRacDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LyRacDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
